-- Insert accounts for 50 users with randomly generated data

INSERT INTO 
	accounts (user_id, billing_address, payment_method, payment_status, payment_provider) 
VALUES
(1, '123 Main St, Springfield, IL', 'Credit Card', 'active', 'Stripe'),
(2, '456 Oak Rd, Denver, CO', 'PayPal', 'active', 'PayPal'),
(3, '789 Pine Ln, Austin, TX', 'Credit Card', 'active', 'Square'),
(4, '101 Maple Dr, Orlando, FL', 'Debit Card', 'active', 'Stripe'),
(5, '202 Birch Blvd, Seattle, WA', 'Credit Card', 'active', 'PayPal'),
(6, '303 Cedar Ave, Miami, FL', 'PayPal', 'active', 'PayPal'),
(7, '404 Elm St, New York, NY', 'Debit Card', 'inactive', 'Square'),
(8, '505 Pine St, Los Angeles, CA', 'Credit Card', 'active', 'Stripe'),
(9, '606 Oak Ave, Boston, MA', 'Credit Card', 'active', 'PayPal'),
(10, '707 Birch Rd, Chicago, IL', 'PayPal', 'inactive', 'Square'),
(11, '808 Maple Ln, Houston, TX', 'Debit Card', 'active', 'Stripe'),
(12, '909 Cedar Dr, Atlanta, GA', 'Credit Card', 'inactive', 'PayPal'),
(13, '1010 Pine Blvd, Phoenix, AZ', 'PayPal', 'active', 'PayPal'),
(14, '1111 Oak Rd, Portland, OR', 'Credit Card', 'inactive', 'Stripe'),
(15, '1212 Birch St, Dallas, TX', 'Debit Card', 'active', 'Square'),
(16, '1313 Maple Ave, Salt Lake City, UT', 'Credit Card', 'active', 'PayPal'),
(17, '1414 Cedar Dr, Las Vegas, NV', 'PayPal', 'active', 'Stripe'),
(18, '1515 Pine St, San Francisco, CA', 'Debit Card', 'active', 'PayPal'),
(19, '1616 Oak Blvd, San Diego, CA', 'Credit Card', 'inactive', 'Stripe'),
(20, '1717 Birch Rd, Denver, CO', 'PayPal', 'active', 'Square'),
(21, '1818 Maple Ln, Minneapolis, MN', 'Credit Card', 'active', 'PayPal'),
(22, '1919 Cedar Ave, Charlotte, NC', 'Debit Card', 'active', 'Stripe'),
(23, '2020 Pine Dr, Indianapolis, IN', 'Credit Card', 'inactive', 'Square'),
(24, '2121 Oak Blvd, Nashville, TN', 'PayPal', 'active', 'PayPal'),
(25, '2222 Birch Rd, Kansas City, MO', 'Debit Card', 'active', 'Stripe'),
(26, '2323 Maple St, Richmond, VA', 'Credit Card', 'inactive', 'Stripe'),
(27, '2424 Cedar Ln, Raleigh, NC', 'PayPal', 'active', 'PayPal'),
(28, '2525 Pine Dr, Jacksonville, FL', 'Credit Card', 'inactive', 'Square'),
(29, '2626 Oak Rd, Sacramento, CA', 'Debit Card', 'active', 'PayPal'),
(30, '2727 Birch St, Tampa, FL', 'Credit Card', 'active', 'Stripe'),
(31, '2828 Maple Ave, Detroit, MI', 'PayPal', 'inactive', 'Square'),
(32, '2929 Cedar Blvd, Columbus, OH', 'Debit Card', 'active', 'Stripe'),
(33, '3030 Pine Ln, Cleveland, OH', 'Credit Card', 'active', 'PayPal'),
(34, '3131 Oak Ave, St. Louis, MO', 'PayPal', 'active', 'PayPal'),
(35, '3232 Birch Dr, Milwaukee, WI', 'Credit Card', 'inactive', 'Stripe'),
(36, '3333 Maple St, Louisville, KY', 'Debit Card', 'active', 'Square'),
(37, '3434 Cedar Rd, Oklahoma City, OK', 'PayPal', 'active', 'Stripe'),
(38, '3535 Pine Blvd, Albuquerque, NM', 'Credit Card', 'inactive', 'PayPal'),
(39, '3636 Oak Ln, Tucson, AZ', 'Debit Card', 'active', 'Stripe'),
(40, '3737 Birch Rd, Omaha, NE', 'PayPal', 'active', 'Square'),
(41, '3838 Maple Ave, Hartford, CT', 'Credit Card', 'active', 'PayPal'),
(42, '3939 Cedar Blvd, New Orleans, LA', 'Debit Card', 'inactive', 'Stripe'),
(43, '4040 Pine Ln, Providence, RI', 'Credit Card', 'active', 'PayPal'),
(44, '4141 Oak Rd, Boise, ID', 'PayPal', 'active', 'Square'),
(45, '4242 Birch Ave, Anchorage, AK', 'Debit Card', 'active', 'Stripe'),
(46, '4343 Maple Blvd, Richmond, VA', 'Credit Card', 'inactive', 'PayPal'),
(47, '4444 Cedar St, Bismarck, ND', 'PayPal', 'active', 'Stripe'),
(48, '4545 Pine Rd, Jackson, MS', 'Debit Card', 'active', 'PayPal'),
(49, '4646 Oak Ave, Boise, ID', 'Credit Card', 'inactive', 'Square'),
(50, '4747 Birch Dr, Tallahassee, FL', 'PayPal', 'active', 'Stripe');

